2022-09-04 19:11:34,398 INFO: PolyTicks startup [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\__init__.py:46]
2022-09-04 19:11:41,562 INFO: PolyTicks startup [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\__init__.py:46]
2022-09-04 19:13:28,013 INFO: PolyTicks startup [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\__init__.py:46]
2022-09-04 19:13:58,583 ERROR: Exception on / [GET] [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\routes.py", line 30, in index
    if posts.has_next else None
AttributeError: 'list' object has no attribute 'has_next'
2022-09-04 19:14:03,382 ERROR: Exception on /user/Cl0udF1sh [GET] [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\routes.py", line 85, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
AttributeError: 'User' object has no attribute 'posts'
2022-09-04 19:15:24,224 ERROR: Exception on /user/Cl0udF1sh [GET] [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py:1741]
Traceback (most recent call last):
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask\app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\venv\lib\site-packages\flask_login\utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\routes.py", line 85, in user
    posts = user.posts.order_by(Post.timestamp.desc()).paginate(
AttributeError: 'User' object has no attribute 'posts'
2022-09-04 19:17:08,128 INFO: PolyTicks startup [in C:\Users\Cl0ud\OneDrive\Desktop\GitHub\PolyTicks\app\__init__.py:46]
